/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminServiceRequestsRouteImport } from './routes/admin/service-requests'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminEmergencyContactsRouteImport } from './routes/admin/emergency-contacts'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceRequestsRoute = AdminServiceRequestsRouteImport.update({
  id: '/admin/service-requests',
  path: '/admin/service-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmergencyContactsRoute = AdminEmergencyContactsRouteImport.update({
  id: '/admin/emergency-contacts',
  path: '/admin/emergency-contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/emergency-contacts': typeof AdminEmergencyContactsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/emergency-contacts': typeof AdminEmergencyContactsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/emergency-contacts': typeof AdminEmergencyContactsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/service-requests': typeof AdminServiceRequestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/faq'
    | '/safety'
    | '/services'
    | '/status'
    | '/admin/contacts'
    | '/admin/emergency-contacts'
    | '/admin/faqs'
    | '/admin/feedback'
    | '/admin/news'
    | '/admin/service-requests'
    | '/auth/login'
    | '/auth/register'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/faq'
    | '/safety'
    | '/services'
    | '/status'
    | '/admin/contacts'
    | '/admin/emergency-contacts'
    | '/admin/faqs'
    | '/admin/feedback'
    | '/admin/news'
    | '/admin/service-requests'
    | '/auth/login'
    | '/auth/register'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/faq'
    | '/safety'
    | '/services'
    | '/status'
    | '/admin/contacts'
    | '/admin/emergency-contacts'
    | '/admin/faqs'
    | '/admin/feedback'
    | '/admin/news'
    | '/admin/service-requests'
    | '/auth/login'
    | '/auth/register'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  SafetyRoute: typeof SafetyRoute
  ServicesRoute: typeof ServicesRoute
  StatusRoute: typeof StatusRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminEmergencyContactsRoute: typeof AdminEmergencyContactsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminServiceRequestsRoute: typeof AdminServiceRequestsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-requests': {
      id: '/admin/service-requests'
      path: '/admin/service-requests'
      fullPath: '/admin/service-requests'
      preLoaderRoute: typeof AdminServiceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emergency-contacts': {
      id: '/admin/emergency-contacts'
      path: '/admin/emergency-contacts'
      fullPath: '/admin/emergency-contacts'
      preLoaderRoute: typeof AdminEmergencyContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  SafetyRoute: SafetyRoute,
  ServicesRoute: ServicesRoute,
  StatusRoute: StatusRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminEmergencyContactsRoute: AdminEmergencyContactsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminServiceRequestsRoute: AdminServiceRequestsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
